# Auto-generated by .github/workflows/update-image-digests.yml
# Do not edit by hand.
{
  "chaptarr/chaptarr" = {
    "0.9" = "chaptarr/chaptarr@sha256:8e29f4941acaf74c80bba4322237dfd2549816b3dd1b581f176b1be5d1ccb46b";
    "latest" =
      "chaptarr/chaptarr@sha256:ccbe157f88f33d085d12a3e5d7cfb9d5b15f89d69b6eba984f789064d21e1b85";
  };
  "ghcr.io/advplyr/audiobookshelf" = {
    "edge" =
      "ghcr.io/advplyr/audiobookshelf@sha256:4d83eb74efdfda1281ad63436a3b70be6f36cf385fb61c73472bbb37d2f55323";
    "latest" =
      "ghcr.io/advplyr/audiobookshelf@sha256:180acad33d69c99ed208676465d8edcb268fa46967735579a7810859885b1a8e";
  };
  "ghcr.io/flaresolverr/flaresolverr" = {
    "latest" =
      "ghcr.io/flaresolverr/flaresolverr@sha256:c80ae007ce2ccdcd217a12426e4f039ef763ff90738c808d38810c3e59323767";
  };
  "ghcr.io/hotio/bazarr" = {
    "latest" =
      "ghcr.io/hotio/bazarr@sha256:ba5deadb451ee2a7a3786f8c9e81123f0548ffa67317c2314d98000beae036d9";
    "nightly" =
      "ghcr.io/hotio/bazarr@sha256:36545f883dc8db507637d7f0791d1cdfcedb3a1e55209839dc6022f65063f104";
    "release" =
      "ghcr.io/hotio/bazarr@sha256:ba5deadb451ee2a7a3786f8c9e81123f0548ffa67317c2314d98000beae036d9";
    "release-v1" =
      "ghcr.io/hotio/bazarr@sha256:ba5deadb451ee2a7a3786f8c9e81123f0548ffa67317c2314d98000beae036d9";
    "release-v1.5" =
      "ghcr.io/hotio/bazarr@sha256:8db8bd2ff0ad23ca111873a5a5be312edf448e74536a5472a0ab02ff36408f76";
    "release-v1.6" =
      "ghcr.io/hotio/bazarr@sha256:ba5deadb451ee2a7a3786f8c9e81123f0548ffa67317c2314d98000beae036d9";
  };
  "ghcr.io/hotio/jellyfin" = {
    "latest" =
      "ghcr.io/hotio/jellyfin@sha256:5a968adf7b41868c4205d0352dee93ecc9ff6d83018d14da00c0dd1a8b191b73";
    "nightly" =
      "ghcr.io/hotio/jellyfin@sha256:4f83e8b54656b446b06fb39156837024cdbdd03a50dae8e47723fb02a84d6df5";
    "release" =
      "ghcr.io/hotio/jellyfin@sha256:5a968adf7b41868c4205d0352dee93ecc9ff6d83018d14da00c0dd1a8b191b73";
    "release-v10" =
      "ghcr.io/hotio/jellyfin@sha256:6bb8b5f815aef0871252445ceaaa4f21ac0dd2bdc05a6f29ce766a9314d3de76";
    "release-v10.11" =
      "ghcr.io/hotio/jellyfin@sha256:6bb8b5f815aef0871252445ceaaa4f21ac0dd2bdc05a6f29ce766a9314d3de76";
  };
  "ghcr.io/hotio/lidarr" = {
    "latest" =
      "ghcr.io/hotio/lidarr@sha256:9eead5e33463693a1afb5a5eeb30368fd2582e79056cc262718447f9749434b2";
    "nightly" =
      "ghcr.io/hotio/lidarr@sha256:1942b87fa8f7e950ab4df276ff367ab959b2b44696e84f280ba7c55c4698c9f5";
    "pr-plugins" =
      "ghcr.io/hotio/lidarr@sha256:ae0b3b14769fdfeb73fe5d9e61ebcda04edf202244bcbd6323d2fe1381154f57";
    "release" =
      "ghcr.io/hotio/lidarr@sha256:9eead5e33463693a1afb5a5eeb30368fd2582e79056cc262718447f9749434b2";
    "testing" =
      "ghcr.io/hotio/lidarr@sha256:28784e7b293b4c2fca350d73531bd48dd2f35c95f117e9266c0f79da928962fe";
  };
  "ghcr.io/hotio/prowlarr" = {
    "latest" =
      "ghcr.io/hotio/prowlarr@sha256:9f5c86207dd6dcc0820ed2940151630ed40d664e6f27f481abf0678d5ab6b2e4";
    "nightly" =
      "ghcr.io/hotio/prowlarr@sha256:49e759e66c88a590f29699ef17b2762443e9562b8efefdf3c52aa51f8acf7cbd";
    "release" =
      "ghcr.io/hotio/prowlarr@sha256:9f5c86207dd6dcc0820ed2940151630ed40d664e6f27f481abf0678d5ab6b2e4";
    "testing" =
      "ghcr.io/hotio/prowlarr@sha256:d4344e43d396e4ca068745d4977c7a25dd5e2bc05b583bd225e082274d1aaefe";
  };
  "ghcr.io/hotio/qbittorrent" = {
    "latest" =
      "ghcr.io/hotio/qbittorrent@sha256:d42ffc026b8c317803ce2ac9611c093dec4ab414f463378ce1b81704a0e0fd22";
    "release" =
      "ghcr.io/hotio/qbittorrent@sha256:d42ffc026b8c317803ce2ac9611c093dec4ab414f463378ce1b81704a0e0fd22";
    "release-v5" =
      "ghcr.io/hotio/qbittorrent@sha256:d42ffc026b8c317803ce2ac9611c093dec4ab414f463378ce1b81704a0e0fd22";
    "release-v5.1" =
      "ghcr.io/hotio/qbittorrent@sha256:a3511925843f3e625ba67a12c36cfaf89762fecc47b6ee064731344d3eef5bdc";
    "release-v5.2" =
      "ghcr.io/hotio/qbittorrent@sha256:d42ffc026b8c317803ce2ac9611c093dec4ab414f463378ce1b81704a0e0fd22";
  };
  "ghcr.io/hotio/radarr" = {
    "latest" =
      "ghcr.io/hotio/radarr@sha256:a85bce11486573ef3811531c927d260fd1b8c495b3a95aa128ea0e89d7bdfed3";
    "nightly" =
      "ghcr.io/hotio/radarr@sha256:e2ddfcf9df7d7453d8048f1621291db671e2905d3f79dc6a26e0ff65a9bdecc8";
    "release" =
      "ghcr.io/hotio/radarr@sha256:a85bce11486573ef3811531c927d260fd1b8c495b3a95aa128ea0e89d7bdfed3";
    "testing" =
      "ghcr.io/hotio/radarr@sha256:4a5b8fef73107fcc76822770457452942bac1bce793bc952fb84437ae92c434b";
  };
  "ghcr.io/hotio/slskd" = {
    "latest" =
      "ghcr.io/hotio/slskd@sha256:52027313cb272413718cf0342206ad5bc7229b19c1641e1e58ec1ee3398ff2b0";
    "nightly" =
      "ghcr.io/hotio/slskd@sha256:85a7df78d8c72b6e9b00c5563be96b9f60410ecc809a36df2984fe4a23b87cfd";
    "release" =
      "ghcr.io/hotio/slskd@sha256:52027313cb272413718cf0342206ad5bc7229b19c1641e1e58ec1ee3398ff2b0";
    "release-v0" =
      "ghcr.io/hotio/slskd@sha256:52027313cb272413718cf0342206ad5bc7229b19c1641e1e58ec1ee3398ff2b0";
    "release-v0.24" =
      "ghcr.io/hotio/slskd@sha256:780076417574e1eb30f6cb5dba5aafecc5ea35e8df77ecd6822fa6181ecf5938";
    "release-v0.25" =
      "ghcr.io/hotio/slskd@sha256:7d58a3af3c2114ad1ee3488bfa9f91062db48c5d027fad5e2d4159e6d439a8a5";
    "release-v0.26" =
      "ghcr.io/hotio/slskd@sha256:52027313cb272413718cf0342206ad5bc7229b19c1641e1e58ec1ee3398ff2b0";
  };
  "ghcr.io/hotio/sonarr" = {
    "latest" =
      "ghcr.io/hotio/sonarr@sha256:3cdb6ff392b0812dcfa32488f4dbe5e2757c154da561a67eb5f19c76ec0057e5";
    "nightly" =
      "ghcr.io/hotio/sonarr@sha256:46e8019018613db14ec24ff171f1cfdb6bfd2dbb7ef7c2720014fcd1df7f3907";
    "release" =
      "ghcr.io/hotio/sonarr@sha256:3cdb6ff392b0812dcfa32488f4dbe5e2757c154da561a67eb5f19c76ec0057e5";
    "v4" =
      "ghcr.io/hotio/sonarr@sha256:68988025f4ffc41dc90fd6d7efa4ab888eecfbb6c87a4a9fd9905cda2ccbc5f2";
  };
  "ghcr.io/itzg/minecraft-server" = {
    "java8" =
      "ghcr.io/itzg/minecraft-server@sha256:3f86cd3268f313b466552cb7ed98c3055f77c21823a7b1fb8426a4f203d7188a";
    "java8-alpine" =
      "ghcr.io/itzg/minecraft-server@sha256:a915facec1b33519287c334f5e8af6fe59e2c92012270f8762bb97f8bda7d57b";
    "java8-graalvm-ce" =
      "ghcr.io/itzg/minecraft-server@sha256:e32cb28f7b4461d0dde930ea9664f613f43248409f13ebf8f569ef6369f43e4a";
    "java8-jdk" =
      "ghcr.io/itzg/minecraft-server@sha256:a3ef2f0d68420a7a497ecb99af0af1d382fb50f50f96ad8e4bd482eda4d1e2b9";
    "java8-multiarch" =
      "ghcr.io/itzg/minecraft-server@sha256:3f86cd3268f313b466552cb7ed98c3055f77c21823a7b1fb8426a4f203d7188a";
    "java8-openj9" =
      "ghcr.io/itzg/minecraft-server@sha256:a4f08f7389ab6177f7fef715d14bbdd1a1b33e0dfaf3f55a758553d9120a45f2";
    "java11" =
      "ghcr.io/itzg/minecraft-server@sha256:5cf7deba40db21532a32cac14525366c459008ca05ff901956d9f20143f45e65";
    "java11-jdk" =
      "ghcr.io/itzg/minecraft-server@sha256:c4e9e78027e10b9993732c79e0aa2a7c4bc089445ef2edde7e91442d5bf4283d";
    "java11-openj9" =
      "ghcr.io/itzg/minecraft-server@sha256:a5bf17aa9f8ed921cfa5092aaf5e7af152eceb73f9338fb25c0b62b478685f84";
    "java16" =
      "ghcr.io/itzg/minecraft-server@sha256:8081a14e0058ebdf3787e992d7f75db5d8f7702c73cf8ede643c8f21e64b13ff";
    "java17" =
      "ghcr.io/itzg/minecraft-server@sha256:0f3419ba7fd40a15f0cef010b51335dfb485232690dedc91d998ea691e40b03e";
    "java17-alpine" =
      "ghcr.io/itzg/minecraft-server@sha256:9e62c88c4785bc37538a2a9e28bbe21c04d4fab5df4163171556636c3f2db075";
    "java17-graalvm" =
      "ghcr.io/itzg/minecraft-server@sha256:41e54392f8b62e09b1f378669dcc8f552a019becb9949d0b5f338ca6c120bef6";
    "java17-graalvm-ce" =
      "ghcr.io/itzg/minecraft-server@sha256:2ce5126ec789b762e003d5cc99231bf5496e4b946e87e4a6be2c67ce50d270c0";
    "java17-jdk" =
      "ghcr.io/itzg/minecraft-server@sha256:ee0e74262fab943ad14b16040f0864957ff94a71726d4d9f265e6c67a17b4d7e";
    "java17-openj9" =
      "ghcr.io/itzg/minecraft-server@sha256:8b66b4fad2da375fdf068256189250165831e7f4b1a9e49409b1c8d8a3a62f01";
    "java19" =
      "ghcr.io/itzg/minecraft-server@sha256:7e05aef132fd726e8c298f52d7bfa042d444af177bc28528dd2064fc49dd51de";
    "java20" =
      "ghcr.io/itzg/minecraft-server@sha256:cd540e587462ff8a2af3eb29dc806d05ff9877d92e6d4ef630ee97d1b09d2248";
    "java20-alpine" =
      "ghcr.io/itzg/minecraft-server@sha256:959a90ef67d750cf8bb980bcdf2759ebc7916f57176cf05443f301497c62b889";
    "java20-graalvm" =
      "ghcr.io/itzg/minecraft-server@sha256:a39b756a708a5be0b85bcab235b61993c2f6d46d8e52d99e82d7b3a46ef2aa60";
    "java21" =
      "ghcr.io/itzg/minecraft-server@sha256:50bdc4b0746c48456d8e737a017786a94c02295b14a8f0f4cb02592a0388cc09";
    "java21-alpine" =
      "ghcr.io/itzg/minecraft-server@sha256:d8b8e3bb964b30f29de1169672ce555d35eb862df64ea84969d58d8d8222aa82";
    "java21-graalvm" =
      "ghcr.io/itzg/minecraft-server@sha256:83c937a49dc3f57bfd6bc003908b8aba9bae41b2f2ba77641c4030343054bf47";
    "java21-jdk" =
      "ghcr.io/itzg/minecraft-server@sha256:d04945b304f2c840fda6ccae9d69bfd3619cf7f7e88f8b210a0ab2dda70bb3a9";
    "java23" =
      "ghcr.io/itzg/minecraft-server@sha256:135f87cf26423ff9a7c191b7b5a4e36bee1f6f4fa8fe36fba952e7a04b59be7e";
    "java23-graalvm" =
      "ghcr.io/itzg/minecraft-server@sha256:fbf62349dc9e17e3af97bfb015eaf519b4dd5012f5c10511046ba5417942a22d";
    "java24" =
      "ghcr.io/itzg/minecraft-server@sha256:7165db25fc99685764ea95edb10438f813622524c6c9eb5f58353e737ede1afd";
    "java24-graalvm" =
      "ghcr.io/itzg/minecraft-server@sha256:b306c76c32a9dab84862f842fc068d963a471dd71acafb97d56a9cf7bc57a541";
    "java25" =
      "ghcr.io/itzg/minecraft-server@sha256:769a826c340586e9d483a0eb6437b8e2c3611aea6a115ff072a2fe372d43e2be";
    "java25-alpine" =
      "ghcr.io/itzg/minecraft-server@sha256:aa430770d112134368da92e05685beb35acba87fceffd0c75dc665b5b6508d3f";
    "java25-graalvm" =
      "ghcr.io/itzg/minecraft-server@sha256:5d95c131cf5d8fe92cf70b9cf86460e6240d16f32e6439194511ca4a7258e1da";
    "java25-jdk" =
      "ghcr.io/itzg/minecraft-server@sha256:876bb38a42b3ed440444c9842f9254c4bc876c9f150a784127ba03a3bb205c51";
    "latest" =
      "ghcr.io/itzg/minecraft-server@sha256:769a826c340586e9d483a0eb6437b8e2c3611aea6a115ff072a2fe372d43e2be";
    "stable" =
      "ghcr.io/itzg/minecraft-server@sha256:e8640538dac5d54c2838d57fa9641e735ad0cf2b71fb0e8a68da3b542a315749";
  };
  "httpd" = {
    "2" = "httpd@sha256:979c38c2228d28c2edfd45c6e27dcee1c7b4a101a5526721ae8ece454e89e99e";
    "2.2" = "httpd@sha256:9784d70c8ea466fabd52b0bc8cde84980324f9612380d22fbad2151df9a430eb";
    "2.4" = "httpd@sha256:979c38c2228d28c2edfd45c6e27dcee1c7b4a101a5526721ae8ece454e89e99e";
    "latest" = "httpd@sha256:979c38c2228d28c2edfd45c6e27dcee1c7b4a101a5526721ae8ece454e89e99e";
  };
}
