# Auto-generated by .github/workflows/update-image-digests.yml
# Do not edit by hand.
{
  "chaptarr/chaptarr" = {
    "0.9" = "chaptarr/chaptarr@sha256:8e29f4941acaf74c80bba4322237dfd2549816b3dd1b581f176b1be5d1ccb46b";
    "latest" =
      "chaptarr/chaptarr@sha256:ccbe157f88f33d085d12a3e5d7cfb9d5b15f89d69b6eba984f789064d21e1b85";
  };
  "ghcr.io/advplyr/audiobookshelf" = {
    "edge" =
      "ghcr.io/advplyr/audiobookshelf@sha256:6fe225ba7401dcc0eb24d2fe98765569d9c4a66b0065e4fb761586ffb910d81d";
    "latest" =
      "ghcr.io/advplyr/audiobookshelf@sha256:3528a93b6442ffe54bd46771bbbab7c97084e1101071586d9dc2254f30bb4358";
  };
  "ghcr.io/flaresolverr/flaresolverr" = {
    "latest" =
      "ghcr.io/flaresolverr/flaresolverr@sha256:c80ae007ce2ccdcd217a12426e4f039ef763ff90738c808d38810c3e59323767";
  };
  "ghcr.io/hotio/bazarr" = {
    "latest" =
      "ghcr.io/hotio/bazarr@sha256:254bd7eebbaef59722ed4b042d634fd2069265537597662b3869defe34768c01";
    "nightly" =
      "ghcr.io/hotio/bazarr@sha256:4425c7dc143714e326449ab8bc83753424cb829ed19e0a95c5fb6585458b9dc8";
    "release" =
      "ghcr.io/hotio/bazarr@sha256:254bd7eebbaef59722ed4b042d634fd2069265537597662b3869defe34768c01";
    "release-v1" =
      "ghcr.io/hotio/bazarr@sha256:254bd7eebbaef59722ed4b042d634fd2069265537597662b3869defe34768c01";
    "release-v1.5" =
      "ghcr.io/hotio/bazarr@sha256:8db8bd2ff0ad23ca111873a5a5be312edf448e74536a5472a0ab02ff36408f76";
    "release-v1.6" =
      "ghcr.io/hotio/bazarr@sha256:254bd7eebbaef59722ed4b042d634fd2069265537597662b3869defe34768c01";
  };
  "ghcr.io/hotio/jellyfin" = {
    "latest" =
      "ghcr.io/hotio/jellyfin@sha256:520070e545f84032f2331f1b40f5c85fab151adcbbf7446dc045e2c64e7ed162";
    "nightly" =
      "ghcr.io/hotio/jellyfin@sha256:5df7310f333629316de69f7157e1d84e04af19e3c7f103ef1363ee52decd2c4b";
    "release" =
      "ghcr.io/hotio/jellyfin@sha256:520070e545f84032f2331f1b40f5c85fab151adcbbf7446dc045e2c64e7ed162";
    "release-v10" =
      "ghcr.io/hotio/jellyfin@sha256:6bb8b5f815aef0871252445ceaaa4f21ac0dd2bdc05a6f29ce766a9314d3de76";
    "release-v10.11" =
      "ghcr.io/hotio/jellyfin@sha256:6bb8b5f815aef0871252445ceaaa4f21ac0dd2bdc05a6f29ce766a9314d3de76";
  };
  "ghcr.io/hotio/lidarr" = {
    "latest" =
      "ghcr.io/hotio/lidarr@sha256:078a839fcd21c529fb96bff132888a0c1c0299ad9611d7e42204f58c04a69a72";
    "nightly" =
      "ghcr.io/hotio/lidarr@sha256:8f60e72483b3c4d70ba949a6c6e4c4edc5006474fa01432d22b259ed4ae0e616";
    "pr-plugins" =
      "ghcr.io/hotio/lidarr@sha256:ae0b3b14769fdfeb73fe5d9e61ebcda04edf202244bcbd6323d2fe1381154f57";
    "release" =
      "ghcr.io/hotio/lidarr@sha256:078a839fcd21c529fb96bff132888a0c1c0299ad9611d7e42204f58c04a69a72";
    "testing" =
      "ghcr.io/hotio/lidarr@sha256:45bd27a1365ec91e9b3e2ce7633a7d2eebf35fec9b1088ae960ec6f05dc3e22c";
  };
  "ghcr.io/hotio/prowlarr" = {
    "latest" =
      "ghcr.io/hotio/prowlarr@sha256:ad8a4defe1837106d238d1f96e4466dab734f4dc3bb74f1fb83b8e33d80c1729";
    "nightly" =
      "ghcr.io/hotio/prowlarr@sha256:5713bb04c5e05ceb3378935bcfe71e53b23089b101b4edf4a5c85eb6e390551d";
    "release" =
      "ghcr.io/hotio/prowlarr@sha256:ad8a4defe1837106d238d1f96e4466dab734f4dc3bb74f1fb83b8e33d80c1729";
    "testing" =
      "ghcr.io/hotio/prowlarr@sha256:c51c6a71e41a60a770360eaa5f8b5e7ae4abe03a2c33a3470be2bfc90570ebe9";
  };
  "ghcr.io/hotio/qbittorrent" = {
    "latest" =
      "ghcr.io/hotio/qbittorrent@sha256:eee3b82d4c081c8f0e9b7909ed7c39fb392d8acb617d3e997eab33b20766c54e";
    "release" =
      "ghcr.io/hotio/qbittorrent@sha256:eee3b82d4c081c8f0e9b7909ed7c39fb392d8acb617d3e997eab33b20766c54e";
    "release-v5" =
      "ghcr.io/hotio/qbittorrent@sha256:eee3b82d4c081c8f0e9b7909ed7c39fb392d8acb617d3e997eab33b20766c54e";
    "release-v5.1" =
      "ghcr.io/hotio/qbittorrent@sha256:a3511925843f3e625ba67a12c36cfaf89762fecc47b6ee064731344d3eef5bdc";
    "release-v5.2" =
      "ghcr.io/hotio/qbittorrent@sha256:eee3b82d4c081c8f0e9b7909ed7c39fb392d8acb617d3e997eab33b20766c54e";
  };
  "ghcr.io/hotio/radarr" = {
    "latest" =
      "ghcr.io/hotio/radarr@sha256:289cb5686dc2292ac4c00ef818ad954b1e4423baffe03e69dd93ebfed38d2fc1";
    "nightly" =
      "ghcr.io/hotio/radarr@sha256:8bc509e56a051cf86f1aec2a5a7eeeb4b0b120716d8e6c10a893d08a2ac6024e";
    "release" =
      "ghcr.io/hotio/radarr@sha256:289cb5686dc2292ac4c00ef818ad954b1e4423baffe03e69dd93ebfed38d2fc1";
    "testing" =
      "ghcr.io/hotio/radarr@sha256:525ebbb34bc6a5fe7fd3357b90ec064ad16a15ed2efce5c6b7434b8c17a81a80";
  };
  "ghcr.io/hotio/slskd" = {
    "latest" =
      "ghcr.io/hotio/slskd@sha256:dd711f67523938e03da10a84a5b3915ce6a36a6b332ec8c2e7dfa6efa8acd91d";
    "nightly" =
      "ghcr.io/hotio/slskd@sha256:6dd0fdaf45f92a1918fa227272b1109a410357f769d92759012f1821f3e24568";
    "release" =
      "ghcr.io/hotio/slskd@sha256:dd711f67523938e03da10a84a5b3915ce6a36a6b332ec8c2e7dfa6efa8acd91d";
    "release-v0" =
      "ghcr.io/hotio/slskd@sha256:dd711f67523938e03da10a84a5b3915ce6a36a6b332ec8c2e7dfa6efa8acd91d";
    "release-v0.24" =
      "ghcr.io/hotio/slskd@sha256:780076417574e1eb30f6cb5dba5aafecc5ea35e8df77ecd6822fa6181ecf5938";
    "release-v0.25" =
      "ghcr.io/hotio/slskd@sha256:7d58a3af3c2114ad1ee3488bfa9f91062db48c5d027fad5e2d4159e6d439a8a5";
    "release-v0.26" =
      "ghcr.io/hotio/slskd@sha256:dd711f67523938e03da10a84a5b3915ce6a36a6b332ec8c2e7dfa6efa8acd91d";
  };
  "ghcr.io/hotio/sonarr" = {
    "latest" =
      "ghcr.io/hotio/sonarr@sha256:4c29ee880945cf42ce3f5d7944ce95145f6120d943f7a912343fe87fb836e63b";
    "nightly" =
      "ghcr.io/hotio/sonarr@sha256:10b2a78fc147cdc2ad3b09b99ba1a3f19e3a423796855482cb6640dce9a60ab5";
    "release" =
      "ghcr.io/hotio/sonarr@sha256:4c29ee880945cf42ce3f5d7944ce95145f6120d943f7a912343fe87fb836e63b";
    "v4" =
      "ghcr.io/hotio/sonarr@sha256:68988025f4ffc41dc90fd6d7efa4ab888eecfbb6c87a4a9fd9905cda2ccbc5f2";
  };
  "ghcr.io/itzg/minecraft-server" = {
    "java8" =
      "ghcr.io/itzg/minecraft-server@sha256:6f263aed44646dc65852d6e5899dc9fcb4bb78dae31a38fc8f791b1396d1ce61";
    "java8-alpine" =
      "ghcr.io/itzg/minecraft-server@sha256:a915facec1b33519287c334f5e8af6fe59e2c92012270f8762bb97f8bda7d57b";
    "java8-graalvm-ce" =
      "ghcr.io/itzg/minecraft-server@sha256:e32cb28f7b4461d0dde930ea9664f613f43248409f13ebf8f569ef6369f43e4a";
    "java8-jdk" =
      "ghcr.io/itzg/minecraft-server@sha256:7903f580986b24a0983ccc016f66c9221a55939e7137156e22ae0c6050c5a2bb";
    "java8-multiarch" =
      "ghcr.io/itzg/minecraft-server@sha256:6f263aed44646dc65852d6e5899dc9fcb4bb78dae31a38fc8f791b1396d1ce61";
    "java8-openj9" =
      "ghcr.io/itzg/minecraft-server@sha256:a4f08f7389ab6177f7fef715d14bbdd1a1b33e0dfaf3f55a758553d9120a45f2";
    "java11" =
      "ghcr.io/itzg/minecraft-server@sha256:d133404399377719c4a0e65593eeb5eb512dd3d0b22f0275c3672890cf0c0000";
    "java11-jdk" =
      "ghcr.io/itzg/minecraft-server@sha256:c4e9e78027e10b9993732c79e0aa2a7c4bc089445ef2edde7e91442d5bf4283d";
    "java11-openj9" =
      "ghcr.io/itzg/minecraft-server@sha256:a5bf17aa9f8ed921cfa5092aaf5e7af152eceb73f9338fb25c0b62b478685f84";
    "java16" =
      "ghcr.io/itzg/minecraft-server@sha256:88c19e6c3aa9fc2d635920e2cabeffbeb65ddb5dd97fa60bfaab1985fdd3e37e";
    "java17" =
      "ghcr.io/itzg/minecraft-server@sha256:cd1004073c208ca27229f3e74219e48b5e1701a0e6fef313113ad753adb14c58";
    "java17-alpine" =
      "ghcr.io/itzg/minecraft-server@sha256:9e62c88c4785bc37538a2a9e28bbe21c04d4fab5df4163171556636c3f2db075";
    "java17-graalvm" =
      "ghcr.io/itzg/minecraft-server@sha256:b6e69f3b959cfcf145bbc4998a342c49bccef775e23d66db1b510a24482e9e70";
    "java17-graalvm-ce" =
      "ghcr.io/itzg/minecraft-server@sha256:2ce5126ec789b762e003d5cc99231bf5496e4b946e87e4a6be2c67ce50d270c0";
    "java17-jdk" =
      "ghcr.io/itzg/minecraft-server@sha256:ee0e74262fab943ad14b16040f0864957ff94a71726d4d9f265e6c67a17b4d7e";
    "java17-openj9" =
      "ghcr.io/itzg/minecraft-server@sha256:8b66b4fad2da375fdf068256189250165831e7f4b1a9e49409b1c8d8a3a62f01";
    "java19" =
      "ghcr.io/itzg/minecraft-server@sha256:7e05aef132fd726e8c298f52d7bfa042d444af177bc28528dd2064fc49dd51de";
    "java20" =
      "ghcr.io/itzg/minecraft-server@sha256:cd540e587462ff8a2af3eb29dc806d05ff9877d92e6d4ef630ee97d1b09d2248";
    "java20-alpine" =
      "ghcr.io/itzg/minecraft-server@sha256:959a90ef67d750cf8bb980bcdf2759ebc7916f57176cf05443f301497c62b889";
    "java20-graalvm" =
      "ghcr.io/itzg/minecraft-server@sha256:a39b756a708a5be0b85bcab235b61993c2f6d46d8e52d99e82d7b3a46ef2aa60";
    "java21" =
      "ghcr.io/itzg/minecraft-server@sha256:5f103c79eab60976d480b97117b58e290ac64bb6fde17b4f809e28996c3e35c2";
    "java21-alpine" =
      "ghcr.io/itzg/minecraft-server@sha256:409c8f0f8f821fc1e0e2aaeff51603338359b8c57486a03cfb936e571f04f5a1";
    "java21-graalvm" =
      "ghcr.io/itzg/minecraft-server@sha256:e26dff051f3d710b5a1558593d0c38e9122292c77f3ce1c39c256ec9c5337aee";
    "java21-jdk" =
      "ghcr.io/itzg/minecraft-server@sha256:3b5728dc50791a4dc3d59ea4ee5e01d0e67f054e1e34e077042a5ead0cac7a9a";
    "java23" =
      "ghcr.io/itzg/minecraft-server@sha256:135f87cf26423ff9a7c191b7b5a4e36bee1f6f4fa8fe36fba952e7a04b59be7e";
    "java23-graalvm" =
      "ghcr.io/itzg/minecraft-server@sha256:fbf62349dc9e17e3af97bfb015eaf519b4dd5012f5c10511046ba5417942a22d";
    "java24" =
      "ghcr.io/itzg/minecraft-server@sha256:7165db25fc99685764ea95edb10438f813622524c6c9eb5f58353e737ede1afd";
    "java24-graalvm" =
      "ghcr.io/itzg/minecraft-server@sha256:b306c76c32a9dab84862f842fc068d963a471dd71acafb97d56a9cf7bc57a541";
    "java25" =
      "ghcr.io/itzg/minecraft-server@sha256:dc7913a69c878594ff7b568862b2cd5541fac6e409d1dc86f0313b1ef7a4d9d4";
    "java25-alpine" =
      "ghcr.io/itzg/minecraft-server@sha256:f32526f13f2735308e8d449d5467bf5732763bddf6ea99d6dcc08f572febe6d2";
    "java25-graalvm" =
      "ghcr.io/itzg/minecraft-server@sha256:d4b54472892ab48c50463b5c717ec7f8c78a9240b65d49f24e524bc644d80703";
    "java25-jdk" =
      "ghcr.io/itzg/minecraft-server@sha256:e952882f9cd31284582d5fc651e38de0dc9ce39a51e81b60c81e1acb46f3b892";
    "latest" =
      "ghcr.io/itzg/minecraft-server@sha256:dc7913a69c878594ff7b568862b2cd5541fac6e409d1dc86f0313b1ef7a4d9d4";
    "stable" =
      "ghcr.io/itzg/minecraft-server@sha256:e8640538dac5d54c2838d57fa9641e735ad0cf2b71fb0e8a68da3b542a315749";
  };
  "httpd" = {
    "2" = "httpd@sha256:979c38c2228d28c2edfd45c6e27dcee1c7b4a101a5526721ae8ece454e89e99e";
    "2.2" = "httpd@sha256:9784d70c8ea466fabd52b0bc8cde84980324f9612380d22fbad2151df9a430eb";
    "2.4" = "httpd@sha256:979c38c2228d28c2edfd45c6e27dcee1c7b4a101a5526721ae8ece454e89e99e";
    "latest" = "httpd@sha256:979c38c2228d28c2edfd45c6e27dcee1c7b4a101a5526721ae8ece454e89e99e";
  };
}
