#!/usr/bin/env bash
set -euo pipefail

IMAGES_FILE="images.txt"
OUTPUT_FILE="images.nix"
PARALLELISM="${PARALLELISM:-32}"
CRANE_TIMEOUT="${CRANE_TIMEOUT:-30}"

# Matches: latest, main, master, edge, nightly, stable, dev, and version
# tags with no patch/build pin, e.g. "v2", "3", "3.11" — but NOT "3.11.4"
# or "3.11.4-alpine". Adjust to taste.
FLOATING_TAG_REGEX="${FLOATING_TAG_REGEX:-^(latest|main|master|edge|nightly|stable|dev|testing|release|v?[0-9]+(\.[0-9]+)?|release-v[0-9]+(\.[0-9]+)?|java[0-9]+(-[a-z0-9]+)*)$}"
pairs="$(mktemp)"
results="$(mktemp)"
trap 'rm -f "$pairs" "$results"' EXIT

grep -vE '^\s*(#|$)' "$IMAGES_FILE" | xargs -n1 | while IFS= read -r image; do
  echo "==> listing tags for $image" >&2
  timeout "$CRANE_TIMEOUT" crane ls "$image" | grep -E "$FLOATING_TAG_REGEX" | while IFS= read -r tag; do
    printf '%s\t%s\n' "$image" "$tag" >> "$pairs"
  done
done

echo "==> $(wc -l < "$pairs") floating tags to resolve" >&2

fetch_digest() {
  local image="$1" tag="$2" digest
  digest="$(timeout "$CRANE_TIMEOUT" crane digest "${image}:${tag}")" || {
    echo "    !! failed/timed out: $image:$tag" >&2
    return 0
  }
  printf '%s\t%s\t%s\n' "$image" "$tag" "$digest"
}
export -f fetch_digest
export CRANE_TIMEOUT

xargs -P "$PARALLELISM" -a "$pairs" -L1 bash -c 'fetch_digest "$1" "$2"' _ > "$results"

{
  echo "# Auto-generated by .github/workflows/update-image-digests.yml"
  echo "# Do not edit by hand."
  echo "{"
  cut -f1 "$results" | sort -u | while IFS= read -r image; do
    echo "  \"$image\" = {"
    awk -F'\t' -v img="$image" '$1 == img' "$results" \
      | sort -t $'\t' -k2,2V \
      | while IFS=$'\t' read -r _ tag digest; do
          echo "    \"$tag\" = \"$image@$digest\";"
        done
    echo "  };"
  done
  echo "}"
} > "$OUTPUT_FILE"
